language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install: true
script: 
  - ./build/linux/build.sh
  - ./build/linux/test.sh
deploy:
  provider: 
    - "heroku"
    app: 
      - "sharon-jd-jobs"
    api_key: 
      - "cfee5907-4e02-41a8-8424-8e612c0d771d"
  on:
    all_branches: true